export enum EventType {
  ORDER_CREATED = "ORDER_CREATED",
  ORDER_CONFIRMED = "ORDER_CONFIRMED",
  ORDER_CANCELLED = "ORDER_CANCELLED",
  ORDER_READY = "ORDER_READY",
  COURIER_ASSIGNED = "COURIER_ASSIGNED",
  ORDER_PICKED_UP = "ORDER_PICKED_UP",
  ORDER_DELIVERED = "ORDER_DELIVERED",
  VENDOR_REGISTERED = "VENDOR_REGISTERED",
  USER_REGISTERED = "USER_REGISTERED",
}
